### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by TalBarami** [open-mmlab/mmcv#1559]
Hey,
I've encountered this CUDA error while attempting to execute script from the mmaction2 repository, but I think it's more related to mmcv.
Upon execution I receive this error:
`RTraceback (most recent call last):
  File "ntu_pose_extraction.py", line 340, in <module>
    anno = ntu_pose_extraction(args.video)
  File "ntu_pose_extraction.py", line 307, in ntu_pose_extraction
    det_results = detection_inference(args, frame_paths)
  File "ntu_pose_extraction.py", line 67, in detection_inference
    result = inference_detector(model, frame_path)
  File "e:\mmdetection\mmdet\apis\inference.py", line 147, in inference_detector
    results = model(return_loss=False, rescale=True, **data)
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "e:\mmdetection\mmdet\models\detectors\base.py", line 174, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "e:\mmdetection\mmdet\models\detectors\base.py", line 147, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "e:\mmdetection\mmdet\models\detectors\two_stage.py", line 179, in simple_test
    proposal_list = self.rpn_head.simple_test_rpn(x, img_metas)
  File "e:\mmdetection\mmdet\models\dense_heads\dense_test_mixins.py", line 130, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas=img_metas)
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\mmcv\runner\fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "e:\mmdetection\mmdet\models\dense_heads\base_dense_head.py", line 96, in get_bboxes
    **kwargs)
  File "e:\mmdetection\mmdet\models\dense_heads\rpn_head.py", line 187, in _get_bboxes_single
    img_shape)
  File "e:\mmdetection\mmdet\models\dense_heads\rpn_head.py", line 232, in _bbox_post_process
    dets, _ = batched_nms(proposals, scores, ids, cfg.nms)
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\mmcv\ops\nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\mmcv\utils\misc.py", line 340, in new_func
    output = old_func(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\mmcv\ops\nms.py", line 172, in nms
    score_threshold, max_num)
  File "C:\Users\owner\anaconda3\envs\mmlab\lib\site-packages\mmcv\ops\nms.py", line 27, in forward
    bboxes, scores, iou_threshold=float(iou_threshold), offset=offset)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1..`

I'm using the following environment:
`'tail' is not recognized as an internal or external command,
operable program or batch file.
'gcc' is not recognized as an internal or external command,
operable program or batch file.
sys.platform: win32
Python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3080
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3
NVCC: Not Available
GCC: n/a
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:

    C++ Version: 199711
    MSVC 192829337
    Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
    Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
    OpenMP 2019
    LAPACK is enabled (usually provided by MKL)
    CPU capability usage: AVX512
    CUDA Runtime 11.3
    NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
    CuDNN 8.2
    Magma 2.5.4
    Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/cb/pytorch_1000000000000/work/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.11.1
OpenCV: 4.5.4
MMCV: 1.4.0
MMCV Compiler: MSVC 192930137
MMCV CUDA Compiler: 11.3
MMAction2: 0.20.0+61d7eb8`

You may find full report of the issue here:
https://github.com/open-mmlab/mmaction2/issues/1308

I have seen more issues related to this error previously, but wasn't unable to solve it.
Your help will be very appreciated.

Thanks,
Tal

**Comment by zhouzaida** [comment]
Hi, what command did you use to install `mmcv-full`? Did you install it from source?

**Comment by TalBarami** [comment]
Hey,
I have installed `mmcv-full` as follows:
`pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/113/1.10.0/index.html`

I think I have solved the problem by installing an older version of `mmcv-full` - currently I am using version 1.3.8.

**Comment by zhouzaida** [comment]
Great
