### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by marsgravity** [open-mmlab/mmcv#2201]
When I use A100 compile mmcv through the source code, used MMCV_WITH_OPS = 1 python install -e . on Linux, then I save mmcv to directory. I repeated the above operation under this directory, but use V100, then I encountered this error.
I've tried many algorithms and they all work like this. Please help me.
Complete error reporting information:
Exception has occurred: RuntimeError
CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
  File "/root/mmcv/mmcv/ops/focal_loss.py", line 60, in forward
    ext_module.sigmoid_focal_loss_forward(
  File "/root/mmdetection/mmdet/models/losses/focal_loss.py", line 139, in sigmoid_focal_loss
    loss = _sigmoid_focal_loss(pred.contiguous(), target.contiguous(), gamma,
  File "/root/mmdetection/mmdet/models/losses/focal_loss.py", line 233, in forward
    loss_cls = self.loss_weight * calculate_loss_func(

**Comment by zhouzaida** [comment]
Hi, you can `export TORCH_CUDA_ARCH_LIST=7.0,8.0` and then build mmcv-full.

**Comment by marsgravity** [comment]
> Hi, you can `export TORCH_CUDA_ARCH_LIST=7.0,8.0` and then build mmcv-full.

thanks, problem solved.
