### ISSUE TITLE
[Bug] 5090显卡无法适配

### ISSUE THREAD

**Issue by 1273603741** [open-mmlab/mmcv#3283]
### Prerequisite

- [x] I have searched [Issues](https://github.com/open-mmlab/mmcv/issues) and [Discussions](https://github.com/open-mmlab/mmcv/discussions) but cannot get the expected help.
- [x] The bug has not been fixed in the latest version(https://github.com/open-mmlab/mmcv).

### Environment

5090显卡根本配不了环境，怎么都是显示mmcv库缺失，cuda12.8赶紧给适配下5090好用啊

### Reproduces the problem - code sample

Traceback (most recent call last):
  File "./tools/train.py", line 287, in <module>
    main()
  File "./tools/train.py", line 276, in main
    train_model(
  File "/home/super/lwy/rcbevdet/mmdet3d/apis/train.py", line 351, in train_model
    train_detector(
  File "/home/super/lwy/rcbevdet/mmdet3d/apis/train.py", line 227, in train_detector
    model = MMDistributedDataParallel(
  File "/home/super/anaconda3/envs/rcbevdet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/super/anaconda3/envs/rcbevdet/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 899262) of binary: /home/super/anaconda3/envs/rcbevdet/bin/python

### Reproduces the problem - command or script

适配5090显卡

### Reproduces the problem - error message

Traceback (most recent call last):
  File "./tools/train.py", line 287, in <module>
    main()
  File "./tools/train.py", line 276, in main
    train_model(
  File "/home/super/lwy/rcbevdet/mmdet3d/apis/train.py", line 351, in train_model
    train_detector(
  File "/home/super/lwy/rcbevdet/mmdet3d/apis/train.py", line 227, in train_detector
    model = MMDistributedDataParallel(
  File "/home/super/anaconda3/envs/rcbevdet/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 646, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/super/anaconda3/envs/rcbevdet/lib/python3.8/site-packages/torch/distributed/utils.py", line 89, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 899262) of binary: /home/super/anaconda3/envs/rcbevdet/bin/python

**Comment by wilsonlv** [comment]
这项目不知道还活着没有，50系列显卡使用cu128各种报错

**Comment by jhluaa** [comment]
same problem

**Comment by jhluaa** [comment]
为什么大家都打马虎眼都是改点东西，改什么却不说

**Comment by 516525465** [comment]
> > > > 这项目不知道还活着没有，50系列显卡使用cu128各种报错
> > > > 可以试试mmcv1.7.2，里面要改些东西才能适配50系显卡
> > 
> > 
> > 请问楼主具体怎么解决的
> 
> 是把mmcv1.7.2下载下来，里面改了些内容，然后还要把代码适配高版本pytorch，弄的挺麻烦的，搞了3个小时才弄好

请问楼主是如何解决的啊？特别希望能换新的50系显卡跑之前的项目，之前
用的0.30.0的mmcv

**Comment by jhluaa** [comment]
改了啥呢，好几天了哥们

**Comment by 1273603741** [comment]
> 摸索出来了哥们们，文档已经整理好了，可以参考一下： https://gitee.com/Wilson_Lws/MuseTalk-50Series-Adaptation/blob/master/README.md

牛逼

**Comment by ShihaoHan19980609** [comment]
直接按照文档里面的源码编译安装成功了，cuda12.8+pytorch2.7

**Comment by shyhoom** [comment]
直接按照官网文档里面的源码编译安装成功了，wsl2里面，cuda12.8+pytorch2.7

**Comment by foundnom** [comment]
直接参考官方文档的源码编译就好了
https://mmcv.readthedocs.io/zh-cn/latest/get_started/build.html

TorchVision: 0.22.1+cu128
OpenCV: 4.11.0
MMEngine: 0.10.7
MMCV: 2.2.0
MMCV Compiler: GCC 11.4
MMCV CUDA Compiler: 12.8

**Comment by STHxiao** [comment]
参考官网文档编译，会报这个错误

<img width="1625" height="428" alt="Image" src="https://github.com/user-attachments/assets/316b0515-19e6-434a-80b8-6b68895788fc" />

**Comment by STHxiao** [comment]
更新一下，bashrc中，第二行这个要注释了才能编译成功

<img width="695" height="91" alt="Image" src="https://github.com/user-attachments/assets/25dc1bb8-5938-4dd1-b488-5bb758f25a56" />

**Comment by Xudada-5566** [comment]
LINK : fatal error LNK1181: 无法打开输入文件“E:\ziliao\mmcv\build\temp.win-amd64-cpython-310\Release\mmcv\ops\csrc\pytorch\cpu\active_rotated_filter.obj”
error: command 'E:\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181

5060 
py3.10
cuda12.8
按照官方编译到这实在进行不下去了

**Comment by STHxiao** [comment]
> LINK : fatal error LNK1181: 无法打开输入文件“E:\ziliao\mmcv\build\temp.win-amd64-cpython-310\Release\mmcv\ops\csrc\pytorch\cpu\active_rotated_filter.obj” error: command 'E:\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe' failed with exit code 1181
> 
> 5060 py3.10 cuda12.8 按照官方编译到这实在进行不下去了

用wsl2，win下可能不太行

**Comment by YGJing7** [comment]
按照源码编译显示安装成功但是运行测试文件显示找不到mmcv._ext

<img width="796" height="205" alt="Image" src="https://github.com/user-attachments/assets/0b183b7a-233b-49e8-b0fc-71a6aa1c3cad" />

**Comment by JillianaaaCHEN** [comment]
> 按照源码编译显示安装成功但是运行测试文件显示找不到mmcv._ext
> 
> <img alt="Image" width="796" height="205" src="https://private-user-images.githubusercontent.com/72682626/493677264-0b183b7a-233b-49e8-b0fc-71a6aa1c3cad.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkxMzMxOTIsIm5iZiI6MTc1OTEzMjg5MiwicGF0aCI6Ii83MjY4MjYyNi80OTM2NzcyNjQtMGIxODNiN2EtMjMzYi00OWU4LWIwZmMtNzFhNmFhMWMzY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI5VDA4MDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZWE2NTA4NTM1MGNkNzk1YmYxMmRlNmRiZTE0OTU4NzM3M2RlOWQ3ODA4YzAzZmY2YzRkYWFlM2NlODVkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zjsxX6krbYdEjwKEWOv89YJTXysE53oKBPWOfblW2z0">

我也遇到这个问题了，请问怎么解决？

**Comment by magirisyang** [comment]
> 直接按照官网文档里面的源码编译安装成功了，wsl2里面，cuda12.8+pytorch2.7

mmcv和mmsegmentation都是按官网文档里源码编译安装的，但按官网文档进行验证时，报错了AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4.目前没找到解决办法，mmcv源码编译安装还能选装2.0.0或2.1.0版本吗？

**Comment by magirisyang** [comment]
> 直接参考官方文档的源码编译就好了 https://mmcv.readthedocs.io/zh-cn/latest/get_started/build.html
> 
> TorchVision: 0.22.1+cu128 OpenCV: 4.11.0 MMEngine: 0.10.7 MMCV: 2.2.0 MMCV Compiler: GCC 11.4MMCV 编译器: GCC 11.4 MMCV CUDA Compiler: 12.8MMCV CUDA 编译器: 12.8

mmcv和mmsegmentation都是按官网文档里源码编译安装的，但按官网文档进行验证时，报错了AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4.目前没找到解决办法，mmcv源码编译安装还能选装2.0.0或2.1.0版本吗？

**Comment by foundnom** [comment]
> > 直接参考官方文档的源码编译就好了 https://mmcv.readthedocs.io/zh-cn/latest/get_started/build.html
> > TorchVision: 0.22.1+cu128 OpenCV: 4.11.0 MMEngine: 0.10.7 MMCV: 2.2.0 MMCV Compiler: GCC 11.4MMCV 编译器: GCC 11.4 MMCV CUDA Compiler: 12.8MMCV CUDA 编译器: 12.8
> 
> mmcv和mmsegmentation都是按官网文档里源码编译安装的，但按官网文档进行验证时，报错了AssertionError: MMCV==2.2.0 is used but incompatible. Please install mmcv>=2.0.0rc4.目前没找到解决办法，mmcv源码编译安装还能选装2.0.0或2.1.0版本吗？

你直接切换到2.0.0rc4编译就好了

**Comment by GiaKhangLuu** [comment]
Hi guys, I am using RTX 5090 and now I am able to build mmcv and mmdet in my environment

This is my screenshot about my env

<img width="1625" height="759" alt="Image" src="https://github.com/user-attachments/assets/e77c7374-6c80-4ab8-b345-94043df1d523" />

The CLIs to install mmcv and mmdet:

```
conda create -n my_env python=3.10
conda activate my_env
pip install scipy==1.15
```

While building `mmdet`, the error while installing scipy would happen, so we installed scipy to counter that

Now, we are going to install `mmengine`, `mmdet`, and `mmcv`, make sure you guys successfully installed `pytorch` and that `pytorch` version able to work with `sm_120` on RTX 5000 series.

```
git clone https://github.com/open-mmlab/mmengine.git && cd mmengine
python3 setup.py install && cd ..

git clone https://github.com/open-mmlab/mmcv.git && cd mmcv
python3 setup.py install && cd ..

git clone https://github.com/open-mmlab/mmdetection.git && cd mmdetection
python3 setup.py install && cd ..
```

**Comment by didier404** [comment]
> 按照源码编译显示安装成功但是运行测试文件显示找不到mmcv._ext
> 
> <img alt="Image" width="796" height="205" src="https://private-user-images.githubusercontent.com/72682626/493677264-0b183b7a-233b-49e8-b0fc-71a6aa1c3cad.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUxODYxMjUsIm5iZiI6MTc2NTE4NTgyNSwicGF0aCI6Ii83MjY4MjYyNi80OTM2NzcyNjQtMGIxODNiN2EtMjMzYi00OWU4LWIwZmMtNzFhNmFhMWMzY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA4VDA5MjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2YwOGEyNTRkNTNhZTU4ZTBkNDJkMTdhZWE5NGJhNjljNTgwZGM3YzFiYzgwODQ1NDRkNWU4NmE2MGNiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RGRL3mIEBBdXljA9pX9TD0J0g5dXJiEg7yY1jvIxjg8">

我也是这样，请问解决了吗

**Comment by GiaKhangLuu** [comment]
> > 按照源码编译显示安装成功但是运行测试文件显示找不到mmcv._ext
> > <img alt="Image" width="796" height="205" src="https://private-user-images.githubusercontent.com/72682626/493677264-0b183b7a-233b-49e8-b0fc-71a6aa1c3cad.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUxODYxMjUsIm5iZiI6MTc2NTE4NTgyNSwicGF0aCI6Ii83MjY4MjYyNi80OTM2NzcyNjQtMGIxODNiN2EtMjMzYi00OWU4LWIwZmMtNzFhNmFhMWMzY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA4VDA5MjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2YwOGEyNTRkNTNhZTU4ZTBkNDJkMTdhZWE5NGJhNjljNTgwZGM3YzFiYzgwODQ1NDRkNWU4NmE2MGNiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RGRL3mIEBBdXljA9pX9TD0J0g5dXJiEg7yY1jvIxjg8">
> 
> 我也是这样，请问解决了吗

Instead of typing 

`pip install -e . -v` as the tutorial.

You should use

`python3 setup.py install`

**Comment by didier404** [comment]
> > > 按照源码编译显示安装成功但是运行测试文件显示找不到mmcv._ext
> > > <img alt="Image" width="796" height="205" src="https://private-user-images.githubusercontent.com/72682626/493677264-0b183b7a-233b-49e8-b0fc-71a6aa1c3cad.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUxODYxMjUsIm5iZiI6MTc2NTE4NTgyNSwicGF0aCI6Ii83MjY4MjYyNi80OTM2NzcyNjQtMGIxODNiN2EtMjMzYi00OWU4LWIwZmMtNzFhNmFhMWMzY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA4VDA5MjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2YwOGEyNTRkNTNhZTU4ZTBkNDJkMTdhZWE5NGJhNjljNTgwZGM3YzFiYzgwODQ1NDRkNWU4NmE2MGNiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RGRL3mIEBBdXljA9pX9TD0J0g5dXJiEg7yY1jvIxjg8">
> > 
> > 
> > 我也是这样，请问解决了吗
> 
> Instead of typing
> 
> `pip install -e . -v` as the tutorial.
> 
> You should use
> 
> `python3 setup.py install`

work for me
THANK YOU

**Comment by alzmzyy** [comment]
> > > > 按照源码编译显示安装成功但是运行测试文件显示找不到mmcv._ext
> > > > <img alt="Image" width="796" height="205" src="https://private-user-images.githubusercontent.com/72682626/493677264-0b183b7a-233b-49e8-b0fc-71a6aa1c3cad.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjUxODYxMjUsIm5iZiI6MTc2NTE4NTgyNSwicGF0aCI6Ii83MjY4MjYyNi80OTM2NzcyNjQtMGIxODNiN2EtMjMzYi00OWU4LWIwZmMtNzFhNmFhMWMzY2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjA4VDA5MjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2M2YwOGEyNTRkNTNhZTU4ZTBkNDJkMTdhZWE5NGJhNjljNTgwZGM3YzFiYzgwODQ1NDRkNWU4NmE2MGNiNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RGRL3mIEBBdXljA9pX9TD0J0g5dXJiEg7yY1jvIxjg8">
> > > 
> > > 
> > > 我也是这样，请问解决了吗
> > 
> > 
> > Instead of typing
> > `pip install -e . -v` as the tutorial.
> > You should use
> > `python3 setup.py install`
> 
> work for me THANK YOU

python3 setup.py install 执行完成后，如果编译出来的库文件_ext.cpython-310-x86_64-linux-gnu.so没有拷贝到mmcv文件夹下还是会报错，要手动copy一下

**Comment by qianjin-g** [comment]
Hello! I successfully compiled mmcv 2.1.0 in a Conda environment using a 5090 GPU and applied it to the mmaction project. My environment configuration is as follows:

- PyTorch version: 2.8.0+cu128
- Torchaudio version: 2.8.0+cu128
- Torchvision version: 0.23.0+cu128
[https://github.com/open-mmlab/mmcv/issues/3319#issuecomment-3789236651]
